export enum Sentimento {
    Ansiosa ,
    Aborrecida,
    Culpada ,
    Entusiasmada,
    Envergonhada,
    Feliz,
    Frustrada,
    Furiosa,
    Irritada,
    Motivada ,
    Orgulhosa,
    Sozinha ,
    Tranquila ,
    Triste ,
}